version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.docker/config.json:/config.json
    command: --interval 10 --label-enable

  game_of_life:
    image: docker.pkg.github.com/julienkeiff/docker-registry/game_of_life:v2.0.1
    hostname: game_of_life
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"

    expose:
      - 3000
    ports:  
      - 1234:3000